import { UserDataProvider } from "@/lib/user-data-context"
import "./globals.css"

export const metadata = {
  title: "Pmgo Espresso",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserDataProvider>{children}</UserDataProvider>
      </body>
    </html>
  )
}
